language: node_js
node_js:
- 10.8.0

branches:
  only:
  - master
cache:
  directories:
  - node_modules
env:
  global:
  - GITHUB_USER: Wadoch
  - GITHUB_REPO: Family-tree-v2
  - secure: "eyN3tyF/xG7c48v5IzjwEZDT6pR2+WHwKUtVbGvKsz5OPKwPG5zmvavUT14JuaDsd2uTBYeOlRLlVsyFH/q8EK9tsI17nr8O1eabeN4KsBMButLsUGM/GpzKI1qh0Q9N7tHSPhZiwf1FB0Us3Mu5eSzI5nggMKBh6w+3l2sWjRkZoF5yp0JGp/MDbyccBBmMynv0f0W5SzUkzhAoH0Eg9kN7mDLJDNhBJ+Ok/v8pORBC5q3ElBMi6eCr3ySI8O6A7lhDW8Td/XNvE1W02yfcYsf60/Ol6Z9fs4lWhFaiKtVbd5VLmNQ8n/3b+LVvwVLwNf1T1TjokZu627i39hdAYPtNkR5Gs24UQz4GhaE5dNJ5j5vDqyjxYSI/NUDug3Bbtacn1UWhta4F7KuLmUBExeEhuDx0BpUAVk4qBOpC9VE5s4lJD6dU1LmG36SGiT0J7iKGsY58s9Ju2+EpTFuLry7puyiHjzqfWbRk2TWZxxTKt34IHkVrqyetRsR0Ns5lQqlS2OvPJrcHbstX1zflVhdEc/TmNmrUgh8nVlixT6/9FdOR+dGVinoOF6Py1AbLlBq9DAUt59Ukkg9QyWU/Fst9Del8LF9JQnL2Zs/viHVxAgYzpX6UhywIlVpzwvPm62cjjGbEz9aHq64e8e8tJBCguGxwOHNVp+BWzsW5wYE="
  #REACT_APP_BFF_URL
  - secure: "kooeMl5CrtfIoDuCc2GS0lu/eM/RY4vBhf/L1bf+vZzIZXuioA0+ZJooKjzZrm6dpeduWPTJ/dpjEvWwG/mWr+XBIRzKumEFTCO1A3hZHxmLIKU1VIjJYMULDAvIEyA4CAWi6TNSAB+dlJJ4BjTS7l88651vA8xdIg9wY/IRG3LOTa4061H9b4LivwbMOuQKqDVIm7dlCG0iSt7dQlWT7IyoI8gWhDLxidmLNAAex3MCbPbQeRcmbl7npn7rkribCQoVcvDQ85iz1TdGsW/9fdIwa0O0FgX5T9Js+JyC4djj509IyAdcNNzfQMO7sq7pmotqcD0IIHc9w8X5E2clj0yrt+e7k5rtv0iRAY4ap/MUpDgbevL+dqmLF3mqc5ONmV/JtQF0cEQzeHJO8yxZkWsczo1pQCYUMQg7x9x2DCBxv3PIK8lfUibJAd0Y9OR0cr7xNJ9ZrcwcMIXbpebkO2mqNx69qWyYNmcd7dioDeJMPoXDW3oTWHVyQHLJnTizg5mJxn7Ifs9GSg+kDEpGXPczzvHmQUbHtTDZYsMEhzz+e4VIIw52fRXfdHH8qDnkEpcyrREfA7Ej52+u4wR5zMSu1wXDATrT/9Qx7ksWYUYhnRdu3UmrSbsWMPe6+a1RtCgezHZX3d21SRTE2Dx7Zl1RdYAKnpcnHytiDKykK4c="

notifications:
  email: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - printf 'yarn-offline-mirror "./.yarn-offline-mirror"\n--production false\n--pure-lockfile true' >> .yarnrc

install:
  - yarn install

script:
  - yarn run build

deploy:
  provider: heroku
  api_key:
    secure: EEys+BOI0HnjopA5TgSRfmC3nJCmgqd1B0TUKjSLKDHCYF78/Nstz2pY4Vb6w1vnJWb5K9SRQRxxe/Fk+tYOS+yKHisDupGKbObg7jyLN2GcBEWIYO0Mw3NWxdADHTvir9/POiQyf0RhMTBHqds5L6tl4MXBiwjXkl6p7cezRJ9NoqEKrEgrKPRW/CKew2RLS6oAA0LORoa/o2qATaSf6oeqBkEcI4yeHLIPKETzz3JmItjUYRJxZTSiavQiPP4cJRVoC5ibYAZKkiqRliScxuYPeuQuDziBwlM6KUKz7pYveM8oUUxXbZ0f4NHsJpR/646yGC++m+lKqlbdK4ylRnl8qm9gbonKOdIoPifXQUn4qo7DmgTaQh40XdN42K4OvEnc5uoHntDl1aG1d4UDRVOzYzx9iBJKxcVftw+Kh3SWvb/7F1Zptkjfn07qASat8tHV6q4kMbOjAfXrHdpQmaOKck3gESpCBRkkiOHVZ0l+yVnTOQJ45hCgkQasVzpsOqcOKV7gfyDSFuiWkgyPjWKs/cOFUtiv1l2HAX4ZPQUng5EzCYXry9mTIMzRBTIw6ObhyVdYX7fvhqFB/QHYRB3g8IJh/iDEuQ5jV76srsRKPA29msNChf7YksYb/sl4tMREYIgTdW/vrM2/z9o1CtrgvGfAko85OM88bZjRZd8=
  skip-cleanup: true
  on:
    branch: master
  app: ps-family-tree