export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const VERIFY_JWT_REQUEST = 'VERIFY_JWT_REQUEST';
export const VERIFY_JWT_SUCCESS = 'VERIFY_JWT_SUCCESS';
export const VERIFY_JWT_FAILURE = 'VERIFY_JWT_FAILURE';