export const GET_ALL_FAMILIES_REQUEST = 'GET_ALL_FAMILIES_REQUEST';
export const GET_ALL_FAMILIES_SUCCESS = 'GET_ALL_FAMILIES_SUCCESS';
export const GET_ALL_FAMILIES_FAILURE = 'GET_ALL_FAMILIES_FAILURE';

export const ADD_NEW_FAMILY_REQUEST = 'ADD_NEW_FAMILY_REQUEST';
export const ADD_NEW_FAMILY_SUCCESS = 'ADD_NEW_FAMILY_SUCCESS';
export const ADD_NEW_FAMILY_FAILURE = 'ADD_NEW_FAMILY_FAILURE';

export const REMOVE_FAMILY_REQUEST = 'REMOVE_FAMILY_REQUEST';
export const REMOVE_FAMILY_SUCCESS = 'REMOVE_FAMILY_SUCCESS';
export const REMOVE_FAMILY_FAILURE = 'REMOVE_FAMILY_FAILURE';

export const GET_SINGLE_FAMILY_REQUEST = 'GET_SINGLE_FAMILY_REQUEST';
export const GET_SINGLE_FAMILY_SUCCESS = 'GET_SINGLE_FAMILY_SUCCESS';
export const GET_SINGLE_FAMILY_FAILURE = 'GET_SINGLE_FAMILY_FAILURE';

export const SET_CURRENT_FAMILY = 'SET_CURRENT_FAMILY';