export const ADD_NEW_PERSON_REQUEST = 'ADD_NEW_PERSON_REQUEST';
export const ADD_NEW_PERSON_SUCCESS = 'ADD_NEW_PERSON_SUCCESS';
export const ADD_NEW_PERSON_FAILURE = 'ADD_NEW_PERSON_FAILURE';

export const OPEN_ADD_NEW_PERSON = 'OPEN_ADD_NEW_PERSON';